on: [push, pull_request]

name: tests

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        components: rustfmt, clippy
        override: true
    - run: cargo update
    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings
  checks-cross-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [nightly]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        components: clippy
        override: true
    - run: cargo update
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
  checks-cross-compile-ios:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [nightly]
        cc: [aarch64-apple-ios]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        components: clippy
        override: true
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
  checks-cross-compile-wasm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [nightly]
        cc: [wasm32-unknown-unknown]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        components: clippy
        override: true
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
    - run: cargo update
    - run: cargo clippy --no-default-features --target=${{ matrix.cc }} -- -D warnings
    - run: RUSTFLAGS="--cfg daku" cargo clippy --target=${{ matrix.cc }} -- -D warnings
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        tc: [1.40.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - run: cargo doc
    - run: cargo test --all --all-features
  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        tc: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        override: true
    - run: cargo update
    - run: cargo test --all --all-features
  # TODO: can be merged back into "cross-compile" after MSRV bumped to 1.78
  # only difference is wasi -> wasip1
  cross-compile-msrv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.40.0]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasi
        - x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
  cross-compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [stable, beta, nightly]
        cc:
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
  cross-compile-ios:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [stable, beta, nightly]
        cc: [aarch64-apple-ios]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
  cross-compile-m1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        tc: [stable, beta, nightly]
        cc: [aarch64-apple-darwin]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo update
    - run: cargo build --all-features --target=${{ matrix.cc }}
  cross-compile-wasm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.40.0, stable, beta, nightly]
        cc: [wasm32-unknown-unknown]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
    - run: cargo update
    - run: cargo build --no-default-features --target=${{ matrix.cc }}
    - run: RUSTFLAGS="--cfg daku" cargo build --target=${{ matrix.cc }}
  cross-compile-illumos-and-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.65.0, stable, beta, nightly]
        cc: [x86_64-unknown-illumos]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: clippy
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
  cross-compile-redox-and-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.65.0, stable, beta, nightly]
        cc: [x86_64-unknown-redox]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: clippy
        toolchain: ${{ matrix.tc }}
        target: ${{ matrix.cc }}
        override: true
    - run: cargo build --all-features --target=${{ matrix.cc }}
    - run: cargo clippy --all-features --target=${{ matrix.cc }} -- -D warnings
